### ISSUE TITLE
NoMethodError in PaymentsController#new

### ISSUE THREAD

**Issue by simonhutchings** [gbarillot/atos#4]
When I call Atos.new.request I get this error in the browser "NoMethodError in PaymentsController#new", if I run it in console I get this "NameError: uninitialized constant Atos"

Then gem is in Gemfile, bundle install run, application restarted. Any idea what is happening?

It's a rails 3.1.3 app.

Thanks

Hutch

**Comment by youcefdahmani** [comment]
I have the same probleme

**Comment by youcefdahmani** [comment]
When I try to do Atos.new.request in my OrderController I get this error : 
uninitialized constant OrdersController::Atos
